/*
 * This frame will allow users to publish their storylines to a real server. 
 * 
 * It simply mails an SQL file to the lab's PI on behalf of the user after 
 * the storyline passes a round of sanity tests.
 */
package storyeditor;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.WindowConstants;

/**
 *
 * @author mgohde
 */
public class PublicationFrame extends javax.swing.JFrame 
{
    private Settings settings;
    private Story story;
    
    /**
     * Creates new form PublicationFrame
     */
    public PublicationFrame(Story s, Settings settings) 
    {
        SanityReport r;
        initComponents();
        
        this.setTitle("Story Publication Dialog");
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        
        this.settings=settings;
        
        senderEmailBox.setText(settings.userEmail);
        recipientEmailBox.setText(settings.dbAdminEmail);
        
        //Perform a sanity check on the requested storyline.
        r=s.sanityTest();
        sanityText.setText(r.toString());
        if(r.allGood())
        {
            System.out.printf("Story %s appears to be valid.", s.title);
            
            summaryLabel.setText("PASS");
            summaryLabel.setForeground(Color.green);
        }
        
        else
        {
            publishButton.setEnabled(false);
            summaryLabel.setText("FAIL");
            summaryLabel.setForeground(Color.red);
        }
        
        this.story=s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        publishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sanityText = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        summaryLabel = new javax.swing.JLabel();
        copyToClipboardButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        recipientEmailBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        senderEmailBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        publishButton.setText("Publish");
        publishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Sanity test results:");

        jScrollPane1.setViewportView(sanityText);

        jLabel2.setText("Summary:");

        summaryLabel.setText("pass or fail");

        copyToClipboardButton.setText("Copy report to clipboard");
        copyToClipboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyToClipboardButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("DB Administrator Email Address:");

        recipientEmailBox.setText("someone@somewhere.edu");

        jLabel4.setText("Sender Email Address:");

        senderEmailBox.setText("you@somewhere.edu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(copyToClipboardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(publishButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(summaryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(recipientEmailBox)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(senderEmailBox))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaryLabel)
                    .addComponent(recipientEmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senderEmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publishButton)
                    .addComponent(cancelButton)
                    .addComponent(copyToClipboardButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyToClipboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyToClipboardButtonActionPerformed
        Clipboard c;
        StringSelection s;
        
        c=Toolkit.getDefaultToolkit().getSystemClipboard();
        s=new StringSelection(sanityText.getText());
        c.setContents(s, s);
    }//GEN-LAST:event_copyToClipboardButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private String strUrl(String input)
    {
        char inputArr[]=input.toCharArray();
        String output="";
        
        for(char c:inputArr)
        {
            //These are really just the ASCII codes for these characters.
            if(c==' ')
            {
                output+="%20";
            }
            
            else if(c=='&')
            {
                output+="%26";
            }
            
            else if(c=='<')
            {
                output+="%3C";
            }
            
            else if(c=='>')
            {
                output+="%3E";
            }
            
            else if(c=='#')
            {
                output+="%23";
            }
            
            else if(c=='%')
            {
                output+="%25";
            }
            
            else if(c=='{')
            {
                output+="%7B";
            }
            
            else if(c=='}')
            {
                output+="%7D";
            }
            
            else if(c=='|')
            {
                output+="%7C";
            }
            
            else if(c=='\n')
            {
                output+="%0A";
            }
            
            //else if(c=='\')
            
            //TODO: Implement more of these character replacements.
            
            else
            {
                output+=c;
            }
        }
        
        return output;
    }
    
    private void publishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishButtonActionPerformed
        //String xmlContents=story.generateXML();
        //Commented out so as not to push broken code:
        try
        {
            story.exportAsXML(new File(settings.loadSaveDir+"/"+story.title+".final.xml"));
            String publicationUri="mailto:"+settings.dbAdminEmail+"?subject=Publishing%20"+story.title;
            publicationUri+="&body="+strUrl("Contributor "+settings.userName+" has submitted storyline "+story.title+" for publication. ");
            publicationUri+=strUrl("Please see attached XML representation of the storyline.\n\n");
            publicationUri+=strUrl("Sent from the StoryEditor program.");
            publicationUri+="&attachment="+settings.loadSaveDir+"/"+story.title+".final.xml";

            try
            {
                Desktop.getDesktop().browse(new URI(publicationUri));
            } catch(IOException e)
            {

            } catch(URISyntaxException ex)
            {
                System.err.println("Invalid URI: "+publicationUri);
            }
        } catch(FileNotFoundException exc)
        {
            System.err.println("Could not write to file: "+settings.loadSaveDir+"/"+story.title+".final.xml");
        }
    }//GEN-LAST:event_publishButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton copyToClipboardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton publishButton;
    private javax.swing.JTextField recipientEmailBox;
    private javax.swing.JTextPane sanityText;
    private javax.swing.JTextField senderEmailBox;
    private javax.swing.JLabel summaryLabel;
    // End of variables declaration//GEN-END:variables
}
