/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storyeditor;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author mgohde
 */
public class SettingsFrame extends javax.swing.JFrame {
    private Settings internalSettings;
    private Runnable okButtonCallback, cancelButtonCallback;

    
    /**
     * Creates new form SettingsFrame
     */
    public SettingsFrame(Settings s) {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        internalSettings=s;
        
        //Start by updating all fields:
        settingsFilePath.setText(s.settingsFilePath);
        userNameBox.setText(s.dbUsername);
        passwordBox.setText(s.dbPassword);
        serverBox.setText(s.dbServer);
        dbNameBox.setText(s.dbName);
        loadSavePathBox.setText(s.loadSaveDir);
        
        okButtonCallback=null;
        cancelButtonCallback=null;
        
        setVisible(true);
    }
    
    /**
     * Used to determine if a confirmation dialog should be shown on cancel.
     * @return 
     */
    private boolean fieldsDiffer()
    {
        boolean fieldsSame;
        
        //Nasty boolean mess incoming;
        fieldsSame=true;
        fieldsSame=fieldsSame&&(internalSettings.dbName.equals(dbNameBox.getText()));
        fieldsSame=fieldsSame&&(internalSettings.dbPassword.equals(passwordBox.getText()));
        fieldsSame=fieldsSame&&(internalSettings.dbServer.equals(serverBox.getText()));
        fieldsSame=fieldsSame&&(internalSettings.loadSaveDir.equals(loadSavePathBox.getText()));
        fieldsSame=fieldsSame&&(internalSettings.dbUsername.equals(userNameBox.getText()));
        fieldsSame=fieldsSame&&(internalSettings.settingsFilePath.equals(settingsFilePath.getText()));
        
        return !fieldsSame;
    }
    
    
    public void registerOkButtonCallback(Runnable r)
    {
        okButtonCallback=r;
    }
    
    public void registerCancelButtonCallback(Runnable r)
    {
        cancelButtonCallback=r;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameBox = new javax.swing.JTextField();
        passwordBox = new javax.swing.JPasswordField();
        serverBox = new javax.swing.JTextField();
        dbNameBox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        settingsFilePath = new javax.swing.JLabel();
        settingsFileUpdateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        loadSavePathBox = new javax.swing.JLabel();
        loadSavePathUpdateButton = new javax.swing.JButton();
        storyUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        storyPassword = new javax.swing.JPasswordField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLabel3.setText("Server:");

        jLabel4.setText("Database");

        userNameBox.setText("exampleusername");

        passwordBox.setText("password9000000");

        serverBox.setText("dowell-nudge.colorado.edu");

        dbNameBox.setText("nudge");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(serverBox)
                    .addComponent(userNameBox)
                    .addComponent(passwordBox)
                    .addComponent(dbNameBox))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(serverBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dbNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Database Connection Settings", jPanel1);

        jLabel5.setText("Settings file location:");

        settingsFilePath.setText("/whatever/to/path/yeah");

        settingsFileUpdateButton.setText("Update...");
        settingsFileUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsFileUpdateButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Open/Save file location:");

        loadSavePathBox.setText("/path/to/your/home/dir");

        loadSavePathUpdateButton.setText("Update...");
        loadSavePathUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSavePathUpdateButtonActionPerformed(evt);
            }
        });

        storyUsername.setText("someuser");

        jLabel7.setText("Story storage username:");

        jLabel8.setText("Story storage password:");

        storyPassword.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(settingsFilePath)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(settingsFileUpdateButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(loadSavePathBox)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loadSavePathUpdateButton)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(storyPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(storyUsername, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(settingsFilePath)
                    .addComponent(settingsFileUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(loadSavePathBox)
                    .addComponent(loadSavePathUpdateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storyUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(storyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        tabbedPane.addTab("General Settings", jPanel2);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        //Put all of the changed settings back into the object:
        internalSettings.dbName=dbNameBox.getText();
        internalSettings.dbPassword=passwordBox.getText();
        internalSettings.dbUsername=userNameBox.getText();
        internalSettings.loadSaveDir=loadSavePathBox.getText();
        internalSettings.dbServer=serverBox.getText();
        
        internalSettings.userName=storyUsername.getText();
        internalSettings.password=storyPassword.getText();
        
        if(okButtonCallback!=null)
        {
            okButtonCallback.run();
        }
        
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(fieldsDiffer())
        {
            //At least one field has changed. Determine if the user is sure:
            int val=JOptionPane.showConfirmDialog(this, "At least one field has been changed. Discard changes?", "Discard changes?", JOptionPane.YES_NO_OPTION);
            
            if(val==JOptionPane.NO_OPTION)
            {
                return;
            }
        }
        
        if(cancelButtonCallback!=null)
        {
            cancelButtonCallback.run();
        }
        
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void settingsFileUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsFileUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsFileUpdateButtonActionPerformed

    private void loadSavePathUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSavePathUpdateButtonActionPerformed
        //Allow the user to choose a directory with a jfilechooser:
        JFileChooser jfc=new JFileChooser(internalSettings.loadSaveDir);
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.setAcceptAllFileFilterUsed(false);
        
        if(jfc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            this.loadSavePathBox.setText(jfc.getSelectedFile().toString());
        }
    }//GEN-LAST:event_loadSavePathUpdateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dbNameBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loadSavePathBox;
    private javax.swing.JButton loadSavePathUpdateButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JTextField serverBox;
    private javax.swing.JLabel settingsFilePath;
    private javax.swing.JButton settingsFileUpdateButton;
    private javax.swing.JPasswordField storyPassword;
    private javax.swing.JTextField storyUsername;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField userNameBox;
    // End of variables declaration//GEN-END:variables
}
